name: automerge

on:

  pull_request:

    types:

      - labeled

      - unlabeled

      - synchronize

      - opened

      - edited

      - ready_for_review

      - reopened

      - unlocked

  pull_request_review:

    types:

      - submitted

  check_suite:

    types:

      - completed

  status: {}

jobs:

  automerge:

    runs-on: ubuntu-latest

    steps:
      - name: Get commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})"
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
           GITHUB_TOKEN: "${{ secrets.TOKEN }}"
           MERGE_LABELS: ${{ steps.commit_message.outputs.message }}
           MERGE_COMMIT_MESSAGE_REGEX: (.*)^---
           PULL_REQUEST_TITLE: ${{ steps.commit_message.outputs.message }}
        
