name: docker test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - dev
  pull_request:
    tags:
      - 'v*'
    branches:
     - dev
permissions:
    contents: write
    pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     # - name: Modify Build File
     #   run: sed -i "s|# build|build|g" ./docker-compose.yaml 
       #      && sed -i "s|gitee|github|g" ./docker/Dockerfile

    #  - name: Build Docker Images
    #    run: docker compose up -d --build

     # - name: Use Default Config
   #     run: docker cp docker/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

   #   - name: Run Test Script
     #   run: docker exec yunzai-bot npm --prefix=/app/Yunzai-Bot run test
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.TOKEN }}
          pull-request-header: robot:I have created a release *beep* *boop*.
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - name: Determine version number

        id: versioning

        run: |

          LAST_TAG=$(git describe --abbrev=0 --tags || echo "v3.0")

          if [[ $LAST_TAG =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+)?(-\S+)?$ ]]; then

            MAJOR=${BASH_REMATCH[1]}

            MINOR=${BASH_REMATCH[2]}

            PATCH=${BASH_REMATCH[3]}

            if [ -n "${BASH_REMATCH[4]}" ]; then

              PRE="${BASH_REMATCH[4]}"

              PATCH=$((PATCH + 1))

            fi

          else

            MAJOR=3

            MINOR=0

            PATCH=1

          fi

          VERSION="$MAJOR.$MINOR.$PATCH$PRE"

          echo ::set-output name=version::$VERSION
      - name: Create Tag
       # if: contains(github.ref, 'refs/heads/main')
        run: git tag v${{ steps.versioning.outputs.version }}
        env:
          RELEASE_VERSION: ${{ steps.generate_release_notes.outputs.version }}

      - name: Push Tag
      #  if: contains(github.ref, 'refs/heads/main')
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          tags: true
          branch: dev
      - name: Get commit message

        id: commit_message

        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})"
      - name: Publish Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: Release ${{ steps.versioning.outputs.version }}
          body: |
            ${{ steps.commit_message.outputs.message }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
