name: docker test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - dev
  pull_request:
    tags:
      - 'v*'
    branches:
     - dev
permissions:
    contents: write
    pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     # - name: Modify Build File
     #   run: sed -i "s|# build|build|g" ./docker-compose.yaml 
       #      && sed -i "s|gitee|github|g" ./docker/Dockerfile

    #  - name: Build Docker Images
    #    run: docker compose up -d --build

     # - name: Use Default Config
   #     run: docker cp docker/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

   #   - name: Run Test Script
     #   run: docker exec yunzai-bot npm --prefix=/app/Yunzai-Bot run test
      - uses: google-github-actions/release-please-action@v3
        with:
          package-type: node
          token: ${{ secrets.TOKEN }}
          pull-request-header: 'robot: I have created a release *beep* *boop*.'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - name: Get commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo $COMMIT_MESSAGE >> $GITHUB_ENV
      - name: Automerge
        uses: pascalgn/automerge-action@v0.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          MERGE_LABELS: ${{ steps.commit_message.outputs.message }}
          VERSION_TAG_PREFIX: v
          VERSION_TAG_SUFFIX: ''
          MERGE_COMMIT_MESSAGE_REGEX: (.*)^---
          DRONE_COMMIT_MESSAGE: version bump to ${{ env.VERSION }}
          COMMIT_MESSAGE_SUFFIX: "\n\nThis commit was automatically generated by the release workflow."
          PULL_REQUEST_TITLE: ${{ steps.commit_message.outputs.message }}
 
           
        
