name: docker test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Modify Build File
        run: sed -i "s|# build|build|g" ./docker-compose.yaml 
             && sed -i "s|gitee|github|g" ./docker/Dockerfile

      - name: Build Docker Images
        run: docker compose up -d --build

      - name: Use Default Config
        run: docker cp docker/qq.yaml yunzai-bot:/app/Yunzai-Bot/config/config

      - name: Run Test Script
        run: docker exec yunzai-bot npm --prefix=/app/Yunzai-Bot run test
      - name: Configure GPG key
        run: |
          gpg --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'
      - name: Create Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: Release ${{ steps.release.outputs.version }}
          body: ${{ steps.release.outputs.changelog }}
          prerelease: false
      - name: Sign Tag
        if: env.RELEASE_GPG_SIGN == 'true'
        run: |
         git tag -s ${{ steps.release.outputs.version }} -m "Release ${{ steps.release.outputs.version }}" -u ${{ secrets.GPG_KEY_ID }}
         git push origin ${{ steps.release.outputs.version }}
